spring:
  config:
    import: optional:file:.env[.properties]

stalwart:
  base-url: ${STALWART_BASE_URL}
  username: ${STALWART_TEST_USERNAME}
  password: ${STALWART_TEST_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
