spring:
  config:
    import: optional:file:.env[.properties]

stalwart:
  base-url: ${STALWART_BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
